RSpec/NamedSubject:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/schedule.rb'
