name: Ruby on Rails

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: circleci/mysql:5.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    container:
      image: circleci/ruby:2.6.1-node-browsers
      env:
        BUNDLE_APP_CONFIG: ./.bundle/
        TZ: /usr/share/zoneinfo/Asia/Tokyo

    steps:
    - uses: actions/checkout@v1
    - name: Build and setup
      run: |
        bundle install --clean --jobs 16 --path ./vendor/bundle/ --retry 3 --with pam_authentication --without development production && bundle clean
        bundle exec rake db:create db:schema:load
        bundle exec rspec spec --format progress
